###############################################################
#                   Authelia configuration                    #
###############################################################

theme: dark
jwt_secret: JWTTOKENID

default_redirection_url: https://authelia.example.com

server:
  host: 0.0.0.0
  port: 9091
  theme: dark
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

log:
  log_level: debug
  log_format: text
  log_file_path: /config/authelia.log

totp:
  issuer: example.com
  period: 30
  skew: 1

#duo_api:
#  hostname: duo_api.example.com
#  integration_key: here-the-key
#  secret_key: here-the-secret-key


authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 4
      key_length: 32
      salt_length: 32
      parallelism: 8
      memory: 1024

# Rules applied to everyone
access_control:
  default_policy: deny
  rules:
    ## bypass rule for login
    - domain: authelia.example.com
      policy: bypass
    ## bypass rules for api / trigges / rss / xmltv
    - domain: "*.example.com"
      policy: bypass
      resources:
        - "^/api/.*$"
        - "^/identity/.*$"
        - "^/triggers/.*$"
        - "^/rss/*$"
        - "^/xmltv/*$"
        - "^/liverel.*$"
        - "^/meshagents.*$"
        - "^/meshsettings.*$"
        - "^/agent.*$"
        - "^/control.*$"
        - "^/meshrelay.*$"
        - "^/wl/.*$"
    ## block admin bitwarden.example.com resources
    - domain: "bitwarden.example.com"
      policy: one_factor
      resources:
        - "^/admin.*$"
    ## one factor login 
    - domain: "*.example.com"
      policy: one_factor
    ## deny rule
    - domain: "example.com"
      policy: deny
    - domain: SERVERIP_ID
      policy: deny

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 1h
  inactivity: 10m
  remember_me_duration: 1M  
  domain: example.com

regulation:
  max_retries: 3
  find_time: 60m
  ban_time: 48

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

###############################################################
#                   Authelia configuration                    #
###############################################################
