##############################################################
## This is just a basic config file to get the app to start ##
##############################################################

minimum-age: 2m30s
scan-delay: 15s
scan-stats: 1m

authentication:
  username: <USERNAME>
  password: <PASSWORD>
  
port: 3030
