name: Add contributors

on:
  workflow_run:
    workflows: ["Run CLI"]
    types:
      - completed

jobs:
  addcon:
    name: Add all Contributors to ReadME
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - uses: BobAnkh/add-contributors@master
        with:
          REPO_NAME: 'dockserver/dockserver'
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '4'
          ACCESS_TOKEN: ${{secrets.CR_PAT}}
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          PATH: '/README.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'
