name: Add contributors

on:
  workflow_run:
    workflows: ["Run CLI"]
    types:
      - completed

jobs:
  addcon:
    name: Add all Contributors to ReadME
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - uses: BobAnkh/add-contributors@master
        with:
          REPO_NAME: 'dockserver/dockserver'
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '4'
          ACCESS_TOKEN: "${{ steps.app-token.outputs.token }}"
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          PATH: '/README.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'

  addwiki:
    needs: addcon
    name: Add all Contributors to wiki
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: '0'

      - uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '4'
          ACCESS_TOKEN: "${{ steps.app-token.outputs.token }}"
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          PATH: '/wiki/docs/index.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'
