name: COPY Readme

on:
  workflow_dispatch:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  copymd:
    name: COPY README from Dockserver Container
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.1.4
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: '0'
   
    - name: COPY File 
      run: |
        echo "Overwrite Index.md"
        if test -f "./.github/container.sh"; then
           bash "./.github/container.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}
