name: COPY index

on:
  workflow_dispatch:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  copymd:
    name: COPY index for Dockserver Wiki
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3.5.0
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: '0'
   
    - name: COPY File 
      run: |
        echo "Overwrite Index.md"
        if test -f "./.github/readmove.sh"; then
           bash "./.github/readmove.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}

  crlf:
    name: Check Mixed Line Endings action
    if: ${{ success() }}
    needs: copymd
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: '1'

    - name: Run CRLF changes
      run: |
        echo "Check Mixed Endings"
        if test -f "./.github/crlf.sh"; then
           bash "./.github/crlf.sh"
        fi

  repack:
    name: Run Repack
    if: ${{ success() }}
    needs: [ copymd, crlf ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: '1'

    - name: Run Repack
      run: |
        echo "run repack"
        if test -f "./.github/repack.sh"; then
           bash "./.github/repack.sh"
        fi
