jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - name: GitHub metrics as SVG image
        uses: lowlighter/metrics@v3.18
        with:
          committer_token: ${{ secrets.CR_PAT }}
          config_timezone: 'Europe/Berlin'
          user: dockserver
          repo: dockserver
          template: repository
          plugin_traffic: 'yes'
          plugin_habits: 'yes'
          plugin_habits_facts: 'yes'
          plugin_habits_charts: 'yes'
          plugin_achievements: 'yes'
          plugin_achievements_limit: 0
          plugin_achievements_secrets: 'yes'
          plugin_activity: 'yes'
          plugin_people: 'yes'
          plugin_people_types: 'followers'
          plugin_followup: 'yes'
          plugin_followup_indepth: 'yes'
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'yes'
          plugin_notable_filter: stars:>1000
          plugin_notable_repositories: 'yes'
          plugin_stargazers: 'yes'
          plugin_pagespeed: 'yes'
          plugin_pagespeed_screenshot: 'yes'
          plugin_pagespeed_token: ${{ secrets.PAGESPEED }}
          plugin_pagespeed_url: https://dockserver.io 
          token: ${{ secrets.CR_PAT }}

name: Metrics
'on':
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
